config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  get '/members/my_page' => 'members#show'
  get '/members/edit_page' => 'members#edit'
  patch 'members/update'
  put '/members/update'

  resources :orchestra_managers, only: [:update]

  resources :orchestras, only: [:new, :create, :show] do
    resources :members, only: [:index] do
    end
    resources :instruments, except: [:new] do
      member do
        get :join
        delete :disjoin
      end
    end

    resources :training_days, except: [:new] do
      member do
        get :join
        delete :disjoin
      end
    end
  end
  get '/request_complete' => 'orchestras#complete'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    invitations: 'members/invitations'
  }
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
# frozen_string_literal: true

class Instrument < ApplicationRecord
  has_many :instrument_details, dependent: :destroy
  has_many :members, through: :instrument_details
  belongs_to :orchestra

  validates :name, presence: true
end

app/models/instrument_detail.rb
# frozen_string_literal: true

class InstrumentDetail < ApplicationRecord
  belongs_to :member
  belongs_to :instrument
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, invite_for: 48.hours

  has_many :orchestra_managers, dependent: :destroy
  has_many :orchestras, through: :orchestra_managers

  has_many :instrument_details, dependent: :destroy
  has_many :instruments, through: :instrument_details

  has_many :trainings, dependent: :destroy
  has_many :training_days, through: :trainings

  validates :last_name, :first_name, :last_name_kana, :first_name_kana,
            length: { minimum: 1, maximum: 100 }, presence: true

  def full_name
    last_name + first_name
  end

  def full_name_kana
    last_name_kana + first_name_kana
  end
end

app/models/orchestra.rb
# frozen_string_literal: true

class Orchestra < ApplicationRecord
  has_many :orchestra_managers, dependent: :destroy
  has_many :members, through: :orchestra_managers
  has_many :instruments, dependent: :destroy
  has_many :training_days, dependent: :destroy

  validates :orchestra_name, presence: true
end

app/models/orchestra_manager.rb
# frozen_string_literal: true

class OrchestraManager < ApplicationRecord
  belongs_to :member
  belongs_to :orchestra

  enum is_active: { active: 0, rest: 1, retire: 2 }
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
end

app/models/training.rb
# frozen_string_literal: true

class Training < ApplicationRecord
  belongs_to :training_day
  belongs_to :member
end

app/models/training_day.rb
# frozen_string_literal: true

class TrainingDay < ApplicationRecord
  belongs_to :orchestra
  has_many :trainings, dependent: :destroy
  has_many :members, through: :trainings

  validates :training_day, presence: true
  validates :title,
    length:{ minimum: 1, maximum: 100 },presence: true
  validates :body,
    length:{ minimum: 1, maximum: 1000 },presence: true

  def training_date
    training_day.strftime('%Y年%-m月%-d日 %H時%M分')
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def top; end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  def index
    @orchestra = Orchestra.find(params[:orchestra_id])
  end

  def show
    @member = current_member
  end

  def edit
    @member = current_member
  end

  def update
    @member = current_member
    @member.update(member_params)
    redirect_to members_my_page_path
  end

  def member_params
    params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :is_active)
  end
end

app/controllers/orchestras_controller.rb
# frozen_string_literal: true

class OrchestrasController < ApplicationController
  def new
    @orchestra = Orchestra.new
  end

  def create
    @orchestra = Orchestra.new(orchestra_params)
    @orchestra.members << current_member
    @orchestra.save
    current_member.orchestra_managers.where(orchestra: @orchestra).first.update(leader: true)
    redirect_to request_complete_path
  end

  def complete; end

  def show
    @orchestra = Orchestra.find(params[:id])
    @member = current_member
  end

  def orchestra_params
    params.require(:orchestra).permit(:orchestra_name)
  end
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < ApplicationController
end

app/controllers/trainings_controller.rb
# frozen_string_literal: true

class TrainingsController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/instruments_helper.rb
# frozen_string_literal: true

module InstrumentsHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/helpers/orchestras_helper.rb
# frozen_string_literal: true

module OrchestrasHelper
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper
end

app/helpers/training_days_helper.rb
# frozen_string_literal: true

module TrainingDaysHelper
end

app/helpers/trainings_helper.rb
# frozen_string_literal: true

module TrainingsHelper
end

app/views/orchestras/_list.html.erb
<div class="container-fluid flex-column align-items-center justify-content-center mt-3"> 
  <div class="row">
    <div class="default-button col-12 col-lg-3 d-flex flex-column align-items-center hv-500">
      <%= link_to '楽団ページ',orchestra_path(orchestra.id), class: "btn btn-primary w-50" %><br>
      <%= link_to '楽器パートページ',orchestra_instruments_path(orchestra.id), class: "btn btn-primary w-50" %><br>
      <%= link_to '練習出欠確認ページ', orchestra_training_days_path(orchestra.id), class: "btn btn-primary w-50 px-0" %><br>
      <%= link_to '団員一覧',orchestra_members_path(orchestra.id), class: "btn btn-primary w-50" %><br>
      <%if current_member.orchestra_managers.where(leader: true).count >= 1 %>
      <%= link_to "招待メール送信画面", new_member_invitation_path, class: "btn btn-success text-white w-50 px-0" %><br>
      <% else %>
      <% end %>
    </div>

app/views/orchestras/complete.html.erb
<div class="top-visual" >
  <div class="top-visual-content">
    <h1 class="top-visual-text text-dark pt-4 font-weight-bold">
      申請が完了しました<br>
      楽団が管理者に承認されるまでしばらくお待ちください<br>
      承認の状況はマイページから確認できます<br>
      <%= link_to "マイページ",members_my_page_path,class: 'btn btn-primary' %>
    </h1>
  </div>
</div>

app/views/orchestras/new.html.erb
<div class="flex-column text-center">
  <h1>楽団名作成ページ</h1>
   <%= form_with model: @orchestra,url: '/orchestras',local:true do |f| %>
   <div class="form_group">
     <label for="orchestra_name">楽団名</label><br>
      <%= f.text_field :orchestra_name %>
    </div><br/>
      <%= f.submit '新規登録' ,class: "btn btn-success" %>
   <% end %>
</div>

app/views/orchestras/show.html.erb
<%= render'members/list' %>
<div class="col-12">
  <h2 class="text-center mt-5 pb-0 text-dark"><ins><%= @orchestra.orchestra_name %>のページ</ins></h2>
</div>
<%= render'orchestras/list',orchestra: @orchestra %>


<div class="col-12 col-lg-6">
  <div class="orchestra_main img-fluid">
</div>
</div>
</div>
</div>

app/views/requests/new.html.erb
<h1>楽団名作成ページ</h1>
 <%= form_with model: @orchestra,url: '/requests',local:true do |f| %>
 <div class="form_group">
   <label for="orchestra_name">楽団名</label><br>
    <%= f.text_field :orchestra_name %>
  </div><br/>
    <%= f.submit '新規登録' ,class: "btn btn-success" %>
    <% end %>