config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  get '/members/my_page' => 'members#show'
  get '/members/edit_page' => 'members#edit'
  patch 'members/update'
  put '/members/update'

  resources :orchestra_managers, only: [:update]

  resources :orchestras, only: [:new, :create, :show] do
    resources :members, only: [:index] do
    end
    resources :instruments, except: [:new] do
      member do
        get :join
        delete :disjoin
      end
    end

    resources :training_days, except: [:new] do
      member do
        get :join
        delete :disjoin
      end
    end
  end
  get '/request_complete' => 'orchestras#complete'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    invitations: 'members/invitations'
  }
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
# frozen_string_literal: true

class Instrument < ApplicationRecord
  has_many :instrument_details, dependent: :destroy
  has_many :members, through: :instrument_details
  belongs_to :orchestra

  validates :name, presence: true
end

app/models/instrument_detail.rb
# frozen_string_literal: true

class InstrumentDetail < ApplicationRecord
  belongs_to :member
  belongs_to :instrument
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, invite_for: 48.hours

  has_many :orchestra_managers, dependent: :destroy
  has_many :orchestras, through: :orchestra_managers

  has_many :instrument_details, dependent: :destroy
  has_many :instruments, through: :instrument_details

  has_many :trainings, dependent: :destroy
  has_many :training_days, through: :trainings

  validates :last_name, :first_name, :last_name_kana, :first_name_kana,
            length: { minimum: 1, maximum: 100 }, presence: true

  def full_name
    last_name + first_name
  end

  def full_name_kana
    last_name_kana + first_name_kana
  end
end

app/models/orchestra.rb
# frozen_string_literal: true

class Orchestra < ApplicationRecord
  has_many :orchestra_managers, dependent: :destroy
  has_many :members, through: :orchestra_managers
  has_many :instruments, dependent: :destroy
  has_many :training_days, dependent: :destroy

  validates :orchestra_name, presence: true
end

app/models/orchestra_manager.rb
# frozen_string_literal: true

class OrchestraManager < ApplicationRecord
  belongs_to :member
  belongs_to :orchestra

  enum is_active: { active: 0, rest: 1, retire: 2 }
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
end

app/models/training.rb
# frozen_string_literal: true

class Training < ApplicationRecord
  belongs_to :training_day
  belongs_to :member
end

app/models/training_day.rb
# frozen_string_literal: true

class TrainingDay < ApplicationRecord
  belongs_to :orchestra
  has_many :trainings, dependent: :destroy
  has_many :members, through: :trainings

  validates :training_day, presence: true
  validates :title,
    length:{ minimum: 1, maximum: 100 },presence: true
  validates :body,
    length:{ minimum: 1, maximum: 1000 },presence: true

  def training_date
    training_day.strftime('%Y年%-m月%-d日 %H時%M分')
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def top; end
end

app/controllers/instruments_controller.rb
# frozen_string_literal: true

class InstrumentsController < ApplicationController
  def index
    @orchestra = Orchestra.find(params[:orchestra_id])
    @instrument = Instrument.new(orchestra_id: params[:orchestra_id])
  end

  def create
    @orchestra = current_member.orchestra_managers.where(leader: true, orchestra_id: params[:orchestra_id]).first.orchestra
    if @orchestra.instruments.create(instrument_params)
      redirect_to orchestra_instruments_path(@orchestra.id)
    else
      render :index
    end
  end

  def show
    @instrument = Instrument.find(params[:id])
  end

  def edit
    if current_member.orchestra_managers.exists?(leader: true)
      @instrument = Instrument.find(params[:id])
    else
      render :index
    end
  end

  def update
    @instrument = Instrument.find(params[:id])
    @instrument.update(instrument_params)
    redirect_to orchestra_instruments_path(@instrument.orchestra_id)
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy
    redirect_to orchestra_instruments_path(@instrument.orchestra_id)
  end

  def join
    @instrument = Instrument.find(params[:id])
    current_member.instruments << @instrument
    current_member.save
    redirect_to orchestra_instrument_path(orchestra_id: @instrument.orchestra_id, id: @instrument.id)
  end

  def disjoin
    @instrument = Instrument.find(params[:id])
    @instrument.members.delete(current_member)
    redirect_to orchestra_instrument_path(orchestra_id: @instrument.orchestra_id, id: @instrument.id)
  end

  private

  def instrument_params
    params.require(:instrument).permit(:name, :orchestra_id)
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  def index
    @orchestra = Orchestra.find(params[:orchestra_id])
  end

  def show
    @member = current_member
  end

  def edit
    @member = current_member
  end

  def update
    @member = current_member
    @member.update(member_params)
    redirect_to members_my_page_path
  end

  def member_params
    params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :is_active)
  end
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < ApplicationController
end

app/controllers/trainings_controller.rb
# frozen_string_literal: true

class TrainingsController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/instruments_helper.rb
# frozen_string_literal: true

module InstrumentsHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/helpers/orchestras_helper.rb
# frozen_string_literal: true

module OrchestrasHelper
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper
end

app/helpers/training_days_helper.rb
# frozen_string_literal: true

module TrainingDaysHelper
end

app/helpers/trainings_helper.rb
# frozen_string_literal: true

module TrainingsHelper
end

app/views/instruments/edit.html.erb
<h2 class="text-center mt-5 text-dark"><ins>楽器パート名の編集</ins></h2>
<div class="container-fluid flex-column align-items-center justify-content-center mt-3">
  <div class="row">
    <div class="col text-center">
      <%= form_with model: @instrument, url: orchestra_instrument_path(@instrument.orchestra_id), local: true do |f| %>
      <label for="instrument_name">パート名</label><br>
      <%= f.text_field :name %><br>
      <%= f.submit '変更を保存', class: "btn btn-success mt-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/instruments/index.html.erb
<%= render'members/list' %>
<h2 class="text-center mt-5 pb-0 text-dark"><ins><%= @orchestra.orchestra_name %> の楽器パート一覧</ins></h2>
<%= render'orchestras/list',orchestra: @orchestra %>

<div class="col-12 col-md-7 md-ml-5">
  <div class="col-12 col-md-5 md-ml-5">
    <%if current_member.orchestra_managers.where(leader: true, orchestra_id: @instrument.orchestra_id).exists? %>
    <%= form_with model: @instrument, url: orchestra_instruments_path(@instrument.orchestra_id), local: true do |f| %>
    <label for="instrument_name">楽器パート登録</label><br>
    <%= f.text_field :name, style: "width:90%"%>
    <%= f.hidden_field :orchestra_id %>
    <%= f.submit '新規登録', class: "btn btn-primary mt-2" %>
    <% end %>
    <% end %>
  </div>

<div class="table-responsive mt-3">
  <table class="table col-md-7 md-ml-5 ">
    <% @orchestra.instruments.each do |instrument| %>
      <tr>
        <th scope="col-3"><%= link_to instrument.name,orchestra_instrument_path(orchestra_id: instrument.orchestra_id, id: instrument.id), class: "text-primary" %></th>
        <%if current_member.orchestra_managers.where(leader: true, orchestra_id: @instrument.orchestra_id).exists? %>
          <th scope="col-1"><%= link_to '編集',edit_orchestra_instrument_path(orchestra_id: instrument.orchestra_id, id: instrument.id), class: "btn btn-success btn-sm"%></th>
          <th scope="col-1"><%= link_to '削除',orchestra_instrument_path(orchestra_id: instrument.orchestra_id, id: instrument.id), method: :delete, class: "btn btn-danger btn-sm" %></th>
        <% else %>
        <% end %>
    <% end %>
      </tr>
  </table>
</div>
</div>
</div>

app/views/instruments/show.html.erb
<%= render'members/list' %>
<h2 class="text-center mt-5 pb-0 text-dark"><ins><%=@instrument.name %>パート詳細ページ <%= @instrument.members.count %>人</ins></h2>

<div class="container">
<div class="row">
<div class="col d-flex flex-column align-items-center justify-content-center">
  <div class="button text-center">
    <% if @instrument.members.exclude?(current_member) %>
    <%= link_to 'パートに参加する', join_orchestra_instrument_path(orchestra_id: @instrument.orchestra_id, id: @instrument.id), class: "btn btn-success my-3 center-block" %>
    <% end %>
  </div>


  <div class="col-md-6 d-flex flex-column align-items-center justify-content-center mt-5">
  <table class="table table-striped bg-white">
     <tbody>
      <tr>
    <% @instrument.members.each do |member|%>
    <td><%= member.full_name %></td>
      <% if member == current_member || current_member.orchestra_managers.where(leader: true,orchestra_id: @instrument.orchestra_id).exists? %>
      <td><%= link_to '不参加にする', disjoin_orchestra_instrument_path(orchestra_id: @instrument.orchestra_id, id: @instrument.id),method: :delete, class: "btn btn-danger" %></td>
      <td><% else %></td>
      <% end %>
      </tr>
      <% end %>
       </tbody>
  </table>
    </div>
  </div>
  </div>
  <div class="button text-center">
    <%= link_to 'パート一覧へ戻る', orchestra_instruments_path(orchestra_id: @instrument.orchestra_id), class: "btn btn-primary" %>
  </div>
</div>
</div>