config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  get '/members/my_page' => 'members#show'
  get '/members/edit_page' => 'members#edit'
  patch 'members/update'
  put '/members/update'

  resources :orchestra_managers, only: [:update]

  resources :orchestras, only: [:new, :create, :show] do
    resources :members, only: [:index] do
    end
    resources :instruments, except: [:new] do
      member do
        get :join
        delete :disjoin
      end
    end

    resources :training_days, except: [:new] do
      member do
        get :join
        delete :disjoin
      end
    end
  end
  get '/request_complete' => 'orchestras#complete'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    invitations: 'members/invitations'
  }
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
# frozen_string_literal: true

class Instrument < ApplicationRecord
  has_many :instrument_details, dependent: :destroy
  has_many :members, through: :instrument_details
  belongs_to :orchestra

  validates :name, presence: true
end

app/models/instrument_detail.rb
# frozen_string_literal: true

class InstrumentDetail < ApplicationRecord
  belongs_to :member
  belongs_to :instrument
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, invite_for: 48.hours

  has_many :orchestra_managers, dependent: :destroy
  has_many :orchestras, through: :orchestra_managers

  has_many :instrument_details, dependent: :destroy
  has_many :instruments, through: :instrument_details

  has_many :trainings, dependent: :destroy
  has_many :training_days, through: :trainings

  validates :last_name, :first_name, :last_name_kana, :first_name_kana,
            length: { minimum: 1, maximum: 100 }, presence: true

  def full_name
    last_name + first_name
  end

  def full_name_kana
    last_name_kana + first_name_kana
  end
end

app/models/orchestra.rb
# frozen_string_literal: true

class Orchestra < ApplicationRecord
  has_many :orchestra_managers, dependent: :destroy
  has_many :members, through: :orchestra_managers
  has_many :instruments, dependent: :destroy
  has_many :training_days, dependent: :destroy

  validates :orchestra_name, presence: true
end

app/models/orchestra_manager.rb
# frozen_string_literal: true

class OrchestraManager < ApplicationRecord
  belongs_to :member
  belongs_to :orchestra

  enum is_active: { active: 0, rest: 1, retire: 2 }
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
end

app/models/training.rb
# frozen_string_literal: true

class Training < ApplicationRecord
  belongs_to :training_day
  belongs_to :member
end

app/models/training_day.rb
# frozen_string_literal: true

class TrainingDay < ApplicationRecord
  belongs_to :orchestra
  has_many :trainings, dependent: :destroy
  has_many :members, through: :trainings

  validates :training_day, presence: true
  validates :title,
    length:{ minimum: 1, maximum: 100 },presence: true
  validates :body,
    length:{ minimum: 1, maximum: 1000 },presence: true

  def training_date
    training_day.strftime('%Y年%-m月%-d日 %H時%M分')
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def top; end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  def index
    @orchestra = Orchestra.find(params[:orchestra_id])
  end

  def show
    @member = current_member
  end

  def edit
    @member = current_member
  end

  def update
    @member = current_member
    @member.update(member_params)
    redirect_to members_my_page_path
  end

  def member_params
    params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :is_active)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/instruments_helper.rb
# frozen_string_literal: true

module InstrumentsHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/helpers/orchestras_helper.rb
# frozen_string_literal: true

module OrchestrasHelper
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper
end

app/helpers/training_days_helper.rb
# frozen_string_literal: true

module TrainingDaysHelper
end

app/helpers/trainings_helper.rb
# frozen_string_literal: true

module TrainingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GakudanNoWa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
　　<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <%= stylesheet_link_tag    'main/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'main/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column ">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container mt-0">
          <div class="navbar-brand pt-0 pl-5 mr-0" href="/"><%= link_to image_tag('logo.3.0.png'), root_path %></div>
          <h5 class="col-5">楽団のためのSNSサイト</h5>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto d-flex align-items-end">
            <% if member_signed_in? %>
              <li>
               <%= link_to "マイページ",members_my_page_path,class: 'fas fa-home nav-link text-dark' %>
              </li>
              <li>
               <%= link_to "ログアウト", destroy_member_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-dark' %>
              </li>
            <% else %>
              <li>
               <%= link_to "ログイン", member_session_path,class: 'fas fa-sign-out-alt nav-link text-dark' %>
              </li>
              <li>
               <%= link_to "楽団の利用申請", new_member_registration_path,class: 'fas fa-solid fa-pen-fancy nav-link text-dark' %><br>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
   <%= yield %>
  </body>
</html>