config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  get '/members/my_page' => 'members#show'
  get '/members/edit_page' => 'members#edit'
  patch 'members/update'
  put '/members/update'

  resources :orchestra_managers, only: [:update]

  resources :orchestras, only: [:new, :create, :show] do
    resources :members, only: [:index] do
    end
    resources :instruments, except: [:new] do
      member do
        get :join
        delete :disjoin
      end
    end

    resources :training_days, except: [:new] do
      member do
        get :join
        delete :disjoin
      end
    end
  end
  get '/request_complete' => 'orchestras#complete'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    invitations: 'members/invitations'
  }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, invite_for: 48.hours

  has_many :orchestra_managers, dependent: :destroy
  has_many :orchestras, through: :orchestra_managers

  has_many :instrument_details, dependent: :destroy
  has_many :instruments, through: :instrument_details

  has_many :trainings, dependent: :destroy
  has_many :training_days, through: :trainings

  validates :last_name, :first_name, :last_name_kana, :first_name_kana,
            length: { minimum: 1, maximum: 100 }, presence: true

  def full_name
    last_name + first_name
  end

  def full_name_kana
    last_name_kana + first_name_kana
  end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

module Members
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/members/invitations_controller.rb
# frozen_string_literal: true

module Members
  class InvitationsController < Devise::InvitationsController
    def new
      super
      @orchestra = current_member.orchestra_managers.where(leader: true)
    end

    def create
      super
      @orchestra = Orchestra.find(params[:member][:orchestra_id])
      @orchestra.members << resource
      flash[:notice] = '招待メールを送信いたしました'
      members_my_page_path
    end

    def edit
      super
      members_my_page_path
    end

    def update
      super
    end

    def destroy
      super
    end

    def member_params
      params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana)
    end
  end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Members
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

module Members
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

module Members
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    def after_sign_up_path_for(_resource)
      new_orchestra_path
    end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

module Members
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    def after_sign_in_path_for(_resource)
      members_my_page_path
    end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

module Members
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  def index
    @orchestra = Orchestra.find(params[:orchestra_id])
  end

  def show
    @member = current_member
  end

  def edit
    @member = current_member
  end

  def update
    @member = current_member
    @member.update(member_params)
    redirect_to members_my_page_path
  end

  def member_params
    params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :is_active)
  end
end

app/helpers/members/invitations_helper.rb
# frozen_string_literal: true

module Members
  module InvitationsHelper
  end
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/views/members/_list.html.erb
<div class="hidden alert-primary text-center"><%= flash[:notice] %></div>

app/views/members/edit.html.erb
<%= render'members/list' %>

<h2 class="text-center mt-3"><%= @member.full_name %>さんの団員情報編集</h2>

<div class="container d-flex flex-column align-items-center justify-content-center mt-3">
  <%= form_with model: @member, url: members_update_path, local: true do |f| %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="last_name mb-0 pb-0"><h5><%= f.label :（姓） %></h5></label>
      <%= f.text_field :last_name,autofocus: true, placeholder:"山田", class: 'form-control', style: "width:90% text-center" %>
    </div>
    <div class="form-group col-md-6">
      <label for="first_name4"><h5><%= f.label :（名） %></h5></label>
      <h5><%= f.text_field :first_name,autofocus: true, placeholder:"太郎", class: 'form-control', style: "width:90% text-center" %></h5>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="last_name4"><h5><%= f.label :（セイ） %></h5></label>
      <h5><%= f.text_field :last_name_kana,autofocus: true,placeholder:"ヤマダ", class: 'form-control', style: "width:90% text-center" %></h5>
    </div>
    <div class="form-group col-md-6">
      <label for="first_name4"><h5><%= f.label :（メイ） %></h5></label>
      <h5><%= f.text_field :first_name_kana,autofocus: true,placeholder:"タロウ", class: 'form-control', style: "width:90% text-center" %></h5>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-10">
      <label for="e-mail4"><h5><%= f.label :メールアドレス %></h5></label>
      <h5><%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder:"sample@gmail.com", class: 'form-control', style: "width:90% text-center"  %></h5>
    </div>
  </div>

  <div class="actions text-center">
    <%= f.submit "変更を保存", class: 'btn btn-primary mb-5' %>
  </div>
  <% end %>
</div>

app/views/members/index.html.erb
<%= render'members/list' %>
<h2 class="text-center mt-5 pb-0 text-dark"><ins><%= @orchestra.orchestra_name %>の団員一覧</ins></h2>
<%= render'orchestras/list',orchestra: @orchestra %>

<div class="table-responsive-sm mt-3 col-lg-8">
  <table class="table table-striped bg-white">
    <tr>
      <% @orchestra.members.each do |member| %>
      <th class="col-4"><h5><%= member.full_name %></h5></th>
        <% member.orchestra_managers.each do |orchestra_manager| %>
          <% if @orchestra.id == orchestra_manager.orchestra_id %>
          <th scope="auto"><h5><%= orchestra_manager.is_active_i18n %></h5></th>
          <% end %>
        <% end %>
        <% if member == current_member || current_member.orchestra_managers.where(leader: true,orchestra: @orchestra).exists? %>
          <th scope="auto"><%= link_to '休団する', orchestra_manager_path(orchestra_id: @orchestra.id, id: member.id,is_active: OrchestraManager.is_actives[:rest]),method: :patch, class: "btn btn-primary btn-sm " %></th>
          <th scope="auto"><%= link_to '退団する', orchestra_manager_path(orchestra_id: @orchestra.id, id: member.id,is_active: OrchestraManager.is_actives[:retire]),method: :patch, class: "btn btn-danger btn-sm " %></th>
          <th scope="auto"><%= link_to '復団する', orchestra_manager_path(orchestra_id: @orchestra.id, id: member.id,is_active: OrchestraManager.is_actives[:active]),method: :patch, class: "btn btn-success btn-sm " %></th>
        <% end %>
    </tr>
    <% end %>
  </table>
</div>
</div>

app/views/members/show.html.erb
<%= render'members/list' %>
<h2 class="text-center mt-5"><ins>マイページ</ins></h2>
<div class="container d-flex flex-column align-items-center justify-content-center">

  <div class="row mt-0 ml-3 d-flex flex-column align-items-center">
    <div class="name col-12">
      <div class="font-weight-bolder col-10 mt-3">氏名</div>
        <div class="col-10">
          <%= @member.full_name %>
        </div>
    </div>
    <div class="name-kana col-12">
      <div class="font-weight-bolder col-10 mt-3">カナ</div>
      <div class="col-6">
        <%= @member.full_name_kana %>
      </div>
    </div>
    <div class="e-mail col-12">
      <div class="font-weight-bolder col-10 mt-3">メールアドレス</div>
      <div class="col-6">
        <%= @member.email %>
      </div>
    </div>
    <div class="btn mb-5">
      <%= link_to '編集する', members_edit_page_path, class: "btn btn-success mt-3" %>
    </div>

    <div class="col-12 mt-5 px-0 d-flex flex-column align-items-center">
      <h4 class="font-weight-bold">所属楽団</h4>
      <% @member.orchestra_managers.each do |orchestra_manager| %>
        ★<%= orchestra_manager.orchestra.orchestra_name %><br>
        <% if orchestra_manager.leader == true %>
          (代表者)
        <% else %>
          (一般団員)
        <% end %>
       (<%= orchestra_manager.is_active_i18n %>)
       <% if orchestra_manager.orchestra.approve_flag && orchestra_manager.active? || orchestra_manager.rest? %>
         <%= link_to '楽団ページへ',orchestra_path(orchestra_manager.orchestra_id), class: "btn btn-primary btn-sm" %><br><br>
       <%else %>
         <br><br>
       <% end %>
      <% end %>
    </div>
  </div>